services:
  dinaip:
    image: isma97p/dinaip
    deploy:
      mode: replicated
      replicas: 1
    secrets:
      - dinaip_passwd
    environment:
      - USERNAME=mail
      - ZONES=domain:zon1,zone2.....
      
secrets:
  dinaip_passwd:
    external: true